AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ClaimProcessingAPI:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: app.lambda_handler
      CodeUri: .
      Events:
        API:
          Type: Api
          Properties:
            Path: /predict
            Method: post
